version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4711" # Internal, not exposed to the world
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:5173" # Exposed to the world
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
