services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "${BACKEND_PORT:-4711}"
    environment:
      BACKEND_PORT: 4711
      BACKEND_HOST: api.rechnung.invinciboll.org
      FRONTEND_PORT: 443
      FRONTEND_HOST: rechnung.invinciboll.org
      OUTPUT_DIR: output
      PRINTER_IP: 192.168.2.134
    networks:
      - caddy-proxy_caddy
    volumes:
      - /home/sboll/Projects/boll-it/test-output:/app/output

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_HOST: api.rechnung.invinciboll.org
        VITE_BACKEND_PORT: 443
    container_name: frontend
    expose:
      - "4712" # Exposed to the world
    depends_on:
      - backend
    networks:
      - caddy-proxy_caddy

networks:
  caddy-proxy_caddy:
    external: true
