services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      BACKEND_PORT: 80
      BACKEND_HOST: api.rechnung.cloud.boll-bau.de
      FRONTEND_PORT: 80
      FRONTEND_HOST: rechnung.cloud.boll-bau.de
      OUTPUT_DIR: output
      PRINTER_IP: 192.168.2.130
    networks:
      - caddy-adguard_caddy
    volumes:
      - /mnt/data/rechnungen:/app/output
      - /mnt/data/db:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_HOST: api.rechnung.cloud.boll-bau.de
        VITE_BACKEND_PORT: 80
    container_name: frontend
    depends_on:
      - backend
    networks:
      - caddy-adguard_caddy

networks:
  caddy-adguard_caddy:
    external: true
