services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${BACKEND_PORT:-4711}:${BACKEND_PORT:-4711}"
    environment:
      BACKEND_PORT: 4711
      FRONTEND_PORT: 80 #Ngnix port
      FRONTEND_HOST: localhost
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_HOST: localhost
        VITE_BACKEND_PORT: 4711
    container_name: frontend
    ports:
      - "80:80" # Exposed to the world
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
